# Generated by Django 2.2 on 2019-04-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amountIngred', models.IntegerField()),
                ('timePrepare', models.CharField(max_length=20)),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('О', 'Основные блюда'), ('В', 'Выпечка'), ('З', 'Закуски'), ('Д', 'Десерты'), ('Н', 'Напитки')], default='О', max_length=1)),
                ('author', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('datePublication', models.DateField()),
            ],
        ),
    ]
