# Generated by Django 2.2 on 2019-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookofrecipes', '0003_auto_20190421_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['category'], 'verbose_name': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1, null=True, verbose_name='Количество порций'),
        ),
    ]
