# Generated by Django 2.2 on 2019-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookofrecipes', '0005_auto_20190421_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
    ]
