# Generated by Django 2.2 on 2019-04-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookofrecipes', '0012_auto_20190422_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
