# Generated by Django 2.2 on 2019-04-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookofrecipes', '0014_auto_20190424_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='datePublication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
