# Generated by Django 2.2 on 2019-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookofrecipes', '0015_auto_20190424_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to='static/', verbose_name='Фото'),
        ),
    ]
